#!/usr/bin/env python3
"""Generate ADEQUACY_SUMMARY.md FROM the compiled GAP-2 theorems.

The load-bearing content — each theorem's exact type and its axiom dependencies — is read
out of Lean itself (`#check @decl` and `#print axioms decl`), not hand-typed. So the summary
cannot drift from what actually compiled. Whitespace in the printed types is normalised to a
single line, so the output depends only on the (toolchain-stable) type structure, not on the
pretty-printer's line wrapping.

Usage:
  python3 harness/gap2/gen_adequacy_summary.py            # write ADEQUACY_SUMMARY.md
  python3 harness/gap2/gen_adequacy_summary.py --check    # regenerate to a temp buffer and
                                                          # byte-compare; exit 1 on mismatch
"""
import json, re, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
MAN = json.load(open(ROOT / "release/gap2_manifest.json"))
ATTESTED = list(MAN["attested_declarations"])
OUT = ROOT / "ADEQUACY_SUMMARY.md"

# Human-facing one-liners; the TYPE and AXIOMS come from Lean, not from here.
BLURB = {
    "canonical_unique":      "Two canonical `JNum`s denoting the same exact decimal are equal (well-definedness of \"the value the grammar assigns\").",
    "scanNumber_sound":      "Number soundness: bytes the scanner consumed form a grammatical token denoting exactly the returned value.",
    "parseStrBody_sound'":   "String-body soundness: an accepted body decodes, under the independent `SChars` grammar, to exactly the returned bytes.",
    "struct_sound":          "Structural soundness for values / elements / members (staged length induction).",
    "parseDoc_sound":        "**C2 — document value soundness.** Every accepted document denotes, under the grammar, the value returned for the consumed prefix.",
    "scanNumber_complete":   "Number completeness: every grammatical number token (arbitrary spelling) with a safe tail is scanned to the canonical value.",
    "parseStrBody_complete": "String completeness: every grammatical `SChars` body (arbitrary spelling) is accepted and decoded.",
    "struct_complete":       "Structural completeness: one mutual induction on the grammar derivation forces the parser through every grammatical value/element/member.",
    "C4":                    "**C4 — completeness.** Every grammatical value within the depth limit, followed by a number-safe tail, is accepted at exactly those bytes.",
    "adequacy":              "**Adequacy = C2 ∧ C4** — the top-level claim.",
}


def short(d): return d.split("Cjson.Spec.", 1)[1]


def lean_probe():
    probe = "import Cjson.Spec\nopen Cjson Cjson.Spec\n"
    for d in ATTESTED:
        probe += f"#check @{short(d)}\n#print axioms {short(d)}\n"
    p = ROOT / "lean" / ".vsf_gap2_summary_probe.lean"
    p.write_text(probe)
    try:
        r = subprocess.run(["lake", "env", "lean", str(p)], cwd=ROOT / "lean",
                           capture_output=True, text=True)
    finally:
        p.unlink(missing_ok=True)
    if r.returncode != 0:
        sys.stderr.write(f"lean probe failed ({r.returncode}):\n{r.stderr[:1200]}\n")
        sys.exit(1)
    return r.stdout


AX = re.compile(r"^'(.+)' (?:depends on axioms: \[(.*)\]|(does not depend on any axioms))$")


def parse(out):
    # split into records at every non-indented line; continuation lines are indented
    records, buf = [], []
    for ln in out.splitlines():
        if ln and not ln[0].isspace():
            if buf: records.append(buf)
            buf = []
        buf.append(ln)
    if buf: records.append(buf)

    # `#check @foo` prints `@foo : type` when foo has implicit binders, else `foo : type`
    # (no leading @). Join each record to one normalised line, then classify.
    TYPE = re.compile(r"^@?(\S+) : (.*)$")
    types, axioms = {}, {}
    for rec in records:
        joined = re.sub(r"\s+", " ", " ".join(l.strip() for l in rec)).strip()
        m = AX.match(joined)
        if m:  # #print axioms record
            name = m.group(1).split("Cjson.Spec.")[-1]
            ax = [] if m.group(3) else [a.strip() for a in m.group(2).split(",") if a.strip()]
            axioms[name] = ax
            continue
        tm = TYPE.match(joined)
        if tm:  # #check record
            types[tm.group(1)] = tm.group(2).strip()
    return types, axioms


def render(types, axioms):
    L = []
    L.append("# ADEQUACY_SUMMARY.md")
    L.append("")
    L.append("<!-- GENERATED by harness/gap2/gen_adequacy_summary.py from the compiled theorems.")
    L.append("     DO NOT EDIT BY HAND. Regenerate with:  python3 harness/gap2/gen_adequacy_summary.py")
    L.append("     verify.sh regenerates this into a temp buffer and byte-compares. -->")
    L.append("")
    L.append(f"Toolchain: **{MAN['lean_toolchain']}**, Std only (no Mathlib, no external lake deps).")
    L.append(f"Allowed axioms (Lean's standard three): `{', '.join(MAN['allowed_axioms'])}`.")
    L.append("")
    L.append("Build/verify the entire proof from a clean checkout:")
    L.append("")
    L.append("```")
    L.append("./reproduce.sh")
    L.append("```")
    L.append("")
    L.append("The released artifact (`lean/Cjson.lean` and its imports) is **byte-identical to tag "
             "v1.0.1** and does not import this spec chain; adequacy is verified separately over "
             f"`{MAN['spec_root']}` and pinned by `{MAN['check_module']}`.")
    L.append("")
    L.append("## Top-level claim")
    L.append("")
    L.append("`adequacy : C2 ∧ C4`, where the two conjuncts are the exact `Grammar.lean` Props:")
    L.append("")
    c2, c4 = MAN["adequacy_conjuncts"]["C2"], MAN["adequacy_conjuncts"]["C4"]
    L.append(f"- **C2** = `{c2}`")
    L.append(f"- **C4** = `{c4}`")
    L.append("")
    L.append("Adequacy is **relative to the frozen SPEC grammar**, its depth model, its deliberate "
             "divergences (NUM-EXACT, D-STR-1/2, D-FMT) and its explicit exclusions. It is **not** a "
             "fully verified JSON parser, RFC 8259 conformance, cJSON behavioural equivalence, C3 "
             "(maximal munch), or C5 (rejection).")
    L.append("")
    L.append("## Attested theorems (type and axioms read from the compiler)")
    L.append("")
    L.append("| # | theorem | axioms |")
    L.append("|---|---|---|")
    for i, d in enumerate(ATTESTED, 1):
        n = short(d)
        ax = axioms.get(n)
        axs = "`" + ", ".join(ax) + "`" if ax else "*(none)*"
        L.append(f"| {i} | `{n}` | {axs} |")
    L.append("")
    L.append("Every theorem above depends only on the allowed axioms — no `sorryAx`, no custom axiom.")
    L.append("")
    L.append("## Exact compiled statements")
    L.append("")
    for d in ATTESTED:
        n = short(d)
        L.append(f"### `{n}`")
        L.append("")
        if n in BLURB:
            L.append(BLURB[n])
            L.append("")
        L.append("```lean")
        L.append(f"{n} : {types.get(n, '<type unavailable>')}")
        L.append("```")
        ax = axioms.get(n)
        L.append(f"axioms: `{', '.join(ax)}`" if ax else "axioms: *(none)*")
        L.append("")
    return "\n".join(L).rstrip() + "\n"


def main():
    types, axioms = parse(lean_probe())
    missing = [short(d) for d in ATTESTED if short(d) not in types or short(d) not in axioms]
    if missing:
        sys.stderr.write(f"missing #check/#print output for: {missing}\n"); sys.exit(1)
    content = render(types, axioms)
    if "--check" in sys.argv:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != content:
            sys.stderr.write("ADEQUACY_SUMMARY.md is OUT OF DATE — regenerate and commit.\n")
            sys.exit(1)
        print("ADEQUACY_SUMMARY.md matches a fresh regeneration.")
    else:
        OUT.write_text(content)
        print(f"wrote {OUT.relative_to(ROOT)} ({len(ATTESTED)} theorems)")


if __name__ == "__main__":
    main()
