#!/usr/bin/env python3
"""B3 — non-circular documentation verification.

THE v1.0.0 DEFECT: the old check_claims.py never opened a single .md file. Its "docs="
column was hardcoded integer literals inside the script, so it compared the artifact against
constants in itself. Falsifying a number in README/PAPER/CLAIMS left it passing.

THE FIX. Documented numbers now carry machine-readable markers:

    <!-- claim:fuzz_agree=116476 -->

This script:
  * loads results/canonical/claims.json (generated by gen_claims.py FROM the measurements —
    it contains no literals of its own);
  * parses every marker out of every file in manifest.documented_claim_files;
  * FAILS if a marked value disagrees with the canonical value        (docs falsified);
  * FAILS if a canonical key has no marker anywhere                   (claim unattested);
  * FAILS if a marker names a key that does not exist                 (phantom claim);
  * FAILS if the same key is marked twice with conflicting values     (self-contradiction).

No claim is validated against a literal stored only inside this checker. Regenerating the
data without updating the docs fails; editing the docs without the data fails.
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAN = json.load(open(ROOT / "release/manifest.json"))
CANON_PATH = ROOT / "results/canonical/claims.json"

if not CANON_PATH.exists():
    print(f"FAIL  {CANON_PATH} missing — run harness/gen_claims.py (failing closed)")
    sys.exit(1)
CANON = json.load(open(CANON_PATH))

MARKER = re.compile(r"<!--\s*claim:([A-Za-z0-9_]+)\s*=\s*(.*?)\s*-->")

failures = []
found = {}          # key -> {value: [files]}


def _visible(line):
    """The line with all claim markers stripped — i.e. what a human actually reads."""
    return MARKER.sub("", line)


def _rendered(v):
    """Forms a documented number may legitimately take in prose."""
    out = {str(v)}
    try:
        out.add(f"{int(v):,}")            # 116476 -> "116,476"
    except (TypeError, ValueError):
        pass
    return out


for rel in MAN["documented_claim_files"]:
    p = ROOT / rel
    if not p.exists():
        failures.append(f"documented_claim_file missing: {rel}")
        continue
    for lineno, line in enumerate(p.read_text().splitlines(), 1):
        for m in MARKER.finditer(line):
            key, val = m.group(1), m.group(2)
            found.setdefault(key, {}).setdefault(val, []).append(rel)
            # ADJACENCY: the value must actually appear in the prose on this line, otherwise
            # an attacker could falsify the human-readable number and leave the marker intact.
            vis = _visible(line)
            if not any(f in vis for f in _rendered(val)):
                failures.append(
                    f"MARKER NOT ADJACENT TO ITS NUMBER: {rel}:{lineno} marks "
                    f"`claim:{key}={val}` but no such value appears in the visible text of "
                    f"that line: {vis.strip()[:90]!r}")

# 1. phantom keys / value mismatches / self-contradiction
for key, vals in sorted(found.items()):
    if key not in CANON:
        failures.append(f"PHANTOM CLAIM: marker `claim:{key}` names a key that does not "
                        f"exist in claims.json (files: {sorted({f for v in vals.values() for f in v})})")
        continue
    if len(vals) > 1:
        failures.append(f"SELF-CONTRADICTION: `{key}` is marked with conflicting values "
                        f"{ {v: sorted(set(f)) for v, f in vals.items()} }")
        continue
    doc_val = next(iter(vals))
    canon_val = str(CANON[key])
    if doc_val != canon_val:
        files = sorted(set(next(iter(vals.values()))))
        failures.append(f"DOC FALSIFIED: `{key}` documented as {doc_val!r} in {files} "
                        f"but the measurement says {canon_val!r}")

# 2. canonical claims with no marker anywhere
unattested = sorted(set(CANON) - set(found))
if unattested:
    failures.append(f"UNATTESTED CLAIMS: canonical values with no `<!-- claim:... -->` marker "
                    f"in any documented file: {unattested}")

for key in sorted(found):
    if key in CANON and len(found[key]) == 1 and next(iter(found[key])) == str(CANON[key]):
        files = sorted(set(next(iter(found[key].values()))))
        print(f"  ok    {key:24s} = {CANON[key]!s:<12s} attested in {', '.join(files)}")

if failures:
    print()
    for f in failures:
        print(f"  FAIL  {f}")
    print(f"\n*** DOCUMENTATION CHECK FAILED — {len(failures)} problem(s) ***")
    sys.exit(1)

print(f"\nAll {len(CANON)} canonical claims are marked in the documentation and every marked "
      f"value matches the measurement.")
